export { default as Home } from './Home';
export { default as ArcanaDemo } from './ArcanaDemo';
export { default as NeosyntisDemo } from './NeosyntisDemo';
export { default as MyntrixDemo } from './MyntrixDemo';
export { default as NotFound } from './not-found';
export { default as Auth } from './Auth';
export { default as VerifyEmail } from './VerifyEmail';
export { default as WaitingForVerification } from './WaitingForVerification';
export { default as PricingPage } from './PricingPage';