import { useState, useRef, useEffect } from 'react';

import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Badge } from '../ui/badge';
import { ScrollArea } from '../ui/scroll-area';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '../ui/collapsible';
import { Send, Paperclip, ChevronDown, Sparkles, Save, Play } from 'lucide-react';
import { mockChatMessages } from '@/pages/Dashboard/client/src/lib/mockApi';

export default function ChatInterfaceTab() {
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState(mockChatMessages);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = () => {
    if (!input.trim()) return;

    const userMessage = {
      id: Date.now().toString(),
      role: 'user' as const,
      content: input,
      createdAt: new Date(),
    };

    const assistantMessage = {
      id: (Date.now() + 1).toString(),
      role: 'assistant' as const,
      content: 'This is a simulated AI response. In production, this would be generated by the LLM with streaming support and proper reasoning.',
      reasoning: 'To provide a helpful response, I should acknowledge the user\'s input and provide relevant information based on the context.',
      createdAt: new Date(),
    };

    setMessages([...messages, userMessage, assistantMessage]);
    setInput('');
  };

  return (
    <div className="h-full flex">
      <div className="flex-1 flex flex-col">
        <div className="border-b px-6 py-3 bg-card/50">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-medium">Chat with ARCANA</h3>
              <p className="text-sm text-muted-foreground">Cognitive AI Assistant</p>
            </div>
            <Badge variant="outline">GPT-4</Badge>
          </div>
        </div>

        <ScrollArea className="flex-1 px-6 py-4">
          <div className="space-y-6 max-w-4xl mx-auto">
            {messages.map((message) => (
              <div
                key={message.id}
                className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                <div
                  className={`max-w-[80%] rounded-lg p-4 ${
                    message.role === 'user'
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-card border'
                  }`}
                >
                  {message.reasoning && (
                    <Collapsible className="mb-3">
                      <CollapsibleTrigger className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors w-full">
                        <Sparkles className="h-4 w-4" />
                        <span>Reasoning Process</span>
                        <ChevronDown className="h-4 w-4 ml-auto" />
                      </CollapsibleTrigger>
                      <CollapsibleContent className="mt-2 p-3 bg-muted/50 rounded-md text-sm text-muted-foreground">
                        {message.reasoning}
                      </CollapsibleContent>
                    </Collapsible>
                  )}
                  <div className="text-sm whitespace-pre-wrap leading-relaxed">
                    {message.content}
                  </div>
                  <div className="text-xs text-muted-foreground mt-2 opacity-70">
                    {new Date(message.createdAt).toLocaleTimeString()}
                  </div>
                </div>
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>
        </ScrollArea>

        <div className="border-t p-4 bg-card/50">
          <div className="max-w-4xl mx-auto space-y-3">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Badge variant="outline" className="text-xs">Model: GPT-4</Badge>
              <Badge variant="outline" className="text-xs">Tokens: 2,543 / 8,192</Badge>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="icon" data-testid="button-attach-file">
                <Paperclip className="h-4 w-4" />
              </Button>
              <Input
                placeholder="Type your message..."
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleSend()}
                className="flex-1"
                data-testid="input-chat-message"
              />
              <Button onClick={handleSend} data-testid="button-send-message">
                <Send className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="w-80 border-l bg-card/30">
        <div className="p-4 border-b">
          <h3 className="font-medium text-sm">Context & Memory</h3>
        </div>
        <ScrollArea className="h-[calc(100%-60px)] p-4">
          <div className="space-y-4">
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm">Pinned Datasets</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <div className="flex items-center justify-between text-sm p-2 bg-muted/30 rounded">
                    <span>Code Examples</span>
                    <Badge variant="outline" className="text-xs">8.9k</Badge>
                  </div>
                  <div className="flex items-center justify-between text-sm p-2 bg-muted/30 rounded">
                    <span>Customer Support QA</span>
                    <Badge variant="outline" className="text-xs">15.4k</Badge>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm">Quick Actions</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <Button variant="outline" size="sm" className="w-full justify-start gap-2" data-testid="button-run-myntrix">
                  <Play className="h-4 w-4" />
                  Run in Myntrix
                </Button>
                <Button variant="outline" size="sm" className="w-full justify-start gap-2" data-testid="button-save-neosyntis">
                  <Save className="h-4 w-4" />
                  Save to Neosyntis
                </Button>
              </CardContent>
            </Card>
          </div>
        </ScrollArea>
      </div>
    </div>
  );
}
